use_frameworks!

target 'markymark_Example' do
    pod 'Markymark', :path => '../'
    pod 'SwiftLint'
end

target 'markymark_Tests' do
    inherit! :search_paths
    pod 'Markymark', :path => '../'
end

target 'TodayExtension' do
    inherit! :search_paths
    pod 'Markymark', :path => '../'
end
